### ISSUE TITLE
プレイリストの順序

### ISSUE THREAD

**Issue by ikedashiki** [ktakahiro150397/saikyo-playlist#22]
新しく作成した奴が既存の物と混ざる時にランダムで入るので作成した順で並んでほしい
再生されたら上に来るようにしてほしい

**Comment by ktakahiro150397** [comment]
プレイリスト一覧の表示順序の修正

- 新規作成された場合は一番上にくる
- 再生されたら一番上にくる

**Comment by ktakahiro150397** [comment]
#33 で一旦クローズ
ドラッグドロップによる順序は別issueで対応 → #32
